org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.0
forge_version_range=[47.4.0,)
loader_version_range=[47,)
mapping_channel=official
mapping_version=1.20.1
geckolib_version=4.7.1
dream_sakura_version=0.0.4_data
player_animation_version=1.0.2-rc1+1.20
mod_id=dream_sakura_blue_archive
mod_name=Dream Sakura Blue Archive
mod_license=All Rights Reserved
mod_version=0.0.2_data
mod_group_id=com.core.dream_sakura_blue_archive.ciorastao
mod_authors=CioraSt
mod_description="???????????bug"